### ISSUE TITLE
Design a easter egg UI for user delights

### ISSUE THREAD

**Issue by akiraonstarknet** [Endur-fi/client#60]
Hey, ideate and design some easter egg UI/UX for small user delights.

**Comment by kiyoshizk** [comment]
Hello ser,

i would like to work on this

**Comment by kiyoshizk** [comment]
Please find the below work in the link below

https://www.figma.com/design/cD5kUO8Els7Uc4uLCSI1QI/Staking-liquidity-STRK?node-id=1-10&t=CSumfCsFLBANKdxh-1
